version: '3.1'
services:
    web:
        build:
            context: ./dev/webserver
        ports:
            - "8083:80"
        volumes:
            - "$WEINSTEIN_ROOT:/var/www"
            - ws-dev-storage:/var/www/storage/app
            - ws-dev-public-storage:/var/www/storage/app_public
        env_file: .env.dev

    database:
        volumes:
            - ws-dev-db:/var/lib/mysql
        ports:
            - "33062:3306"

volumes:
    ws-dev-db:
    ws-dev-storage:
    ws-dev-public-storage:
