version: '3.2'
services:
    web:
        image: weinstein/webserver:latest
        ports:
            - "8083:80"
        volumes:
            - "$WEINSTEIN_ROOT:/var/www"
        env_file: .env.dev

    database:
        volumes:
            - ./maria-dev:/var/lib/mysql
        ports:
            - "33062:3306"
