version: '3.1'
services:
    web:
        links:
            - cache
            - database
        environment:
            - "APP_URL=http://localhost:8082"
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "DB_DATABASE=weinstein"
            - "DB_USERNAME=weinstein"
            - "DB_PASSWORD=123456"
            - "SESSION_DRIVER=redis"
        restart: always
    queue-worker:
        links:
            - cache
            - database
        command: php ../artisan queue:work
        environment:
            - "APP_URL=http://localhost:8082"
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "DB_DATABASE=weinstein"
            - "DB_USERNAME=weinstein"
            - "DB_PASSWORD=123456"
            - "SESSION_DRIVER=redis"
        restart: always
    database:
        image: mariadb:10.2
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=weinstein"
            - "MYSQL_USER=weinstein"
            - "MYSQL_PASSWORD=123456"
        restart: always
    cache:
        image: redis:3.0
        restart: always

