version: '2'
services:
    web:
        image: weinstein/web
        ports:
            - "8080:80"
        links:
            - app
    app:
        image: weinstein/app
        links:
            - database
            - cache
        env_file: .env.prod
        volumes:
            - /var/www/storage
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "DB_USER=weinstein"
            - "DB_PASS=123456"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
            - "CACHE_DRIVER=redis"
            - "SESSION_DRIVER=redis"
    database:
        image: mariadb:10.0
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=weinstein"
            - "MYSQL_USER=weinstein"
            - "MYSQL_PASSWORD=123456"
        volumes:
            - ./maria-prod:/var/lib/mysql
    cache:
        image: redis:3.0

