version: '2'
services:
    web:
        image: weinstein/web
        ports:
            - "8080:80"
        links:
            - app
    app:
        image: weinstein/app
        links:
            - database
            - cache
        volumes:
            - ./storage:/var/www/storage
        env_file: .env.prod
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "DB_USER=weinstein"
            - "DB_PASS=123456"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
    database:
        image: mariadb:10.0
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=weinstein"
            - "MYSQL_USER=weinstein"
            - "MYSQL_PASSWORD=123456"
        ports:
            - "33061:3306"
    cache:
        image: redis:3.0
        ports:
            - "63791:6379"
