version: '3.1'
services:
    web:
        image: weinstein/web:production
        ports:
            - "8080:80"
        env_file: .env.prod
    database:
        volumes:
            - ws-prod-db:/var/lib/mysql
volumes:
    ws-prod-db:
