version: '2'
services:
    web:
        image: weinstein/web:production
        ports:
            - "8080:80"
    app:
        image: weinstein/app:production
        env_file: .env.prod
        environment:
            - "DB_USERNAME=weinstein"
            - "DB_PASSWORD=123456"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
            - "CACHE_DRIVER=redis"
            - "SESSION_DRIVER=redis"
    database:
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=weinstein"
            - "MYSQL_PASSWORD=123456"

