version: '2'
services:
    web:
        image: weinstein/web:latest
        ports:
            - "8081:80"
    app:
        image: weinstein/app:latest
        env_file: .env.testing
        environment:
            - "DB_USERNAME=weinstein"
            - "DB_PASSWORD=123456"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
            - "CACHE_DRIVER=redis"
            - "SESSION_DRIVER=redis"
    database:
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=weinstein"
            - "MYSQL_PASSWORD=123456"
        volumes:
            - ./maria-testing:/var/lib/mysql
        ports:
            - "33061:3361"

